### ISSUE TITLE
Reset ViewModel.

### ISSUE THREAD

**Issue by ficmichal** [SamTheDev/SampleMvvmLightNavigation#1]
Hi!
You did a great job with this explanation of navigation between ViewModels. Thank you a lot!

Nevertheless, I have got a one question. How can I reset a ViewModel? Let's say I have finished a game (I am now in a GameOverViewModel) and I want to play again, so a GameViewModel should look like the same, when I started a game.

How can I reach that?

**Comment by SamTh3D3v** [comment]
Unregister then register the VM from the `SimpleIoc`, that should do the trick.

Here, [an article](http://www.mercurynewmedia.com/blog/blog-detail/mercury-new-media-blog/2015/04/30/wpf-clearing-data-context-with-mvvm-light) about that.

**Comment by ficmichal** [comment]
Thank you a lot!
This solution should work.
